version: "2"
services:
  zipkin:
    image: openzipkin/zipkin:latest
    container_name: ozcowms-zipkin
    ports:
      - 9411:9411
    restart: on-failure
  mysql-admin:
    image: phpmyadmin/phpmyadmin:latest
    container_name: ozcowms-mysql-admin
    environment:
      - PMA_HOST=${MYSQL_DB_HOST}
    ports:
      - 80:80
    networks:
      - ozcowms
  user-center:
    image: java:8
    container_name: ozcowms-user-center
    volumes:
      - ./apps/user-${APP_VERSION}.jar:/root/user-${APP_VERSION}.jar
    working_dir: /root
    networks:
      - ozcowms
    entrypoint: java -Xms256M -Xmx256M -jar user-${APP_VERSION}.jar --db.host=${MYSQL_DB_HOST} --nacos.host=${NACOS_HOST} --spring.zipkin.base-url=${ZIPKIN_HOST}
  product:
    image: java:8
    container_name: ozcowms-product
    volumes:
      - ./apps/product-${APP_VERSION}.jar:/root/product-${APP_VERSION}.jar
    working_dir: /root
    networks:
      - ozcowms
    entrypoint: java -Xms256M -Xmx256M -jar product-${APP_VERSION}.jar --db.host=${MYSQL_DB_HOST} --nacos.host=${NACOS_HOST} --spring.zipkin.base-url=${ZIPKIN_HOST}
  miniapp:
    image: java:8
    container_name: ozcowms-miniapp
    volumes:
      - ./apps/miniapp-${APP_VERSION}.jar:/root/miniapp-${APP_VERSION}.jar
    working_dir: /root
    networks:
      - ozcowms
    entrypoint: java -Xms256M -Xmx256M -jar miniapp-${APP_VERSION}.jar --nacos.host=${NACOS_HOST} --spring.zipkin.base-url=${ZIPKIN_HOST}
  gateway:
    image: java:8
    container_name: ozcowms-gateway
    volumes:
      - ./apps/gateway-${APP_VERSION}.jar:/root/gateway-${APP_VERSION}.jar
    ports:
      - 8080:8080
    working_dir: /root
    networks:
      - ozcowms
    entrypoint: java -Xms256M -Xmx256M -jar gateway-${APP_VERSION}.jar --spring.redis.host=${REDIS_DB_HOST} --nacos.host=${NACOS_HOST} --spring.zipkin.base-url=${ZIPKIN_HOST}
networks:
  ozcowms:
    driver: bridge
